### PR TITLE
Handling LARGE files in ::getFile

### PR DESCRIPTION
**Pull request by spiderr**
Ben,

I have added support to allow for ::getFile and ::fetch to send files direct to disk. This avoids PHP memory issues when transferring huge files.

### CODE REVIEW

**Comment by BenExile** [comment]
Hi @spiderr 

Thank you for your hard work. This is a feature I am currently working on in addition to ensuring there are sufficient permissions to write to the file, and whether a file that already exists should be overwritten. For this reason I will not be merging this pull request.

Can I please ask that if you do wish to contribute to this project, that you add a remote for the upstream repository and pull changes before pushing and sending pull requests. I have noticed that some of the changes you made have already been made by myself in previous commits.

Regards,
Ben

**Comment by spiderr** [comment]
Hi Ben,

Sounds like you're going for a more complete solution than me, so I look forward to your implementation. I hope my code helps you out.

Sorry about missing the upstream pull.

**Comment by spiderr** [comment]
Hi Ben,

I just merged to your head. Any progress on saving a file directly? I'd prefer to stay on your mainline.

**Comment by BenExile** [comment]
Hi @spiderr 

I've implemented this in commit fb5a802. At present MIME information is not returned if a file is written directly to disk - this will be addressed in a future commit.

Regards,
Ben

**Pull request closed without merging**
