### PR TITLE
Added a filesystem Storage provider

### PR DESCRIPTION
**Pull request by jschmid**
I added a filesystem Storage provider to be able to permanently store tokens without having to use a database.

### CODE REVIEW

**Comment by BenExile** [comment]
Hi @jschmid 

Thanks for sending this pull request. I'll review shortly. Applications that have a user system are more than likely going to use a database anyway, but I'm open to suggestions of where this may be more appropriate.

I did have a glance and noticed that the code is based on, and almost identical to my PDO handler - in fact there are still references to PDO from where it was copy/pasted. I'd therefore prefer it if you left me as the author but added yourself too. The link to the repository would have to remain pointing to this project to avoid any confusion.

**Comment by jschmid** [comment]
I do have a use case that needs it (where I have only one user and do not want to create a database for that.)
I'll update the source based on your comments.

**Comment by BenExile** [comment]
I suppose this could also be used in situations where there aren't users, but where you would like to connect to a single Dropbox using a persistent token. Good idea - I'll merge shortly.

Thank you

**Comment by jschmid** [comment]
That's what I have. 
a createToken.php called once using the browser.
a cron.php called every day. (In my case that fetches the newspaper and put it as a PDF on my Dropbox)

Let me edit the few things you noticed.

**Comment by jschmid** [comment]
I finally got time to update the comments.
I reverted the header back, removed references to the database.

**Comment by BenExile** [comment]
Hi @jschmid 

I merged and made a few modifications to your code.

The first is adding the setDirectory() method which MUST be called before you can use the Filesystem handler. This is to prevent, where possible, OAuth tokens accidentally being written to a web facing directory on the server.

The second is to MD5 the token file name. This was done to prevent invalid characters being included in the token file name.

Thanks again!

**Pull request merged**
